type Partition {
  tid: ID!
  typename: String!
}

type Video {
  vid: ID!
  author: String!
  duration: String!
  pic: String!
  play: Int!
  title: String!
  description: String!
  review: Int!
  ctime: String!
}

type Tag {
  tid: ID!
  name: String!
  cover: String
  ctime: Int
  type: Int
}

type Query {
  partitionList(tid: ID): [Partition!]!
  rankingVideos(rid: Int, day: Int): [Video!]!
  rankingRegionVideos(rid: Int!, day: Int): [Video!]!
  videoTags(aid: ID!): [Tag!]!
}
